name: Cypress Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress-intermediario-v2

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./cypress-intermediario-v2
        env:
          CI: true